# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-27 04:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resourceId', models.TextField(default='')),
                ('name', models.TextField(default='')),
                ('introduce', models.TextField(default='')),
                ('size', models.TextField(default='')),
                ('uploadTime', models.TextField(default='')),
                ('link', models.TextField(default='')),
            ],
        ),
    ]
