# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-30 03:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
                ('password', models.CharField(default='', max_length=20)),
                ('gender', models.IntegerField(default=0, max_length=1)),
                ('email_username', models.CharField(default='', max_length=20)),
                ('nickname', models.CharField(default='', max_length=20)),
                ('intro', models.TextField(default='')),
            ],
        ),
        migrations.RemoveField(
            model_name='resource',
            name='resourceId',
        ),
        migrations.AlterField(
            model_name='resource',
            name='link',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='resource',
            name='name',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='resource',
            name='size',
            field=models.IntegerField(max_length=11),
        ),
        migrations.AlterField(
            model_name='resource',
            name='uploadTime',
            field=models.DateTimeField(),
        ),
    ]
