# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-30 04:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_auto_20171030_1159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='size',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.IntegerField(default=0),
        ),
    ]
