# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-08 15:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_r_resource_evaluation_r_resource_user_download_r_resource_user_like'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_time', models.DateTimeField(auto_now_add=True)),
                ('report_user_id', models.PositiveIntegerField()),
                ('be_reported_resource_id', models.PositiveIntegerField()),
                ('already_handle', models.BooleanField(default=False)),
            ],
        ),
    ]
