# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-06 23:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_r_resource_evaluation_r_resource_user_download_r_resource_user_like'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='course_code',
            field=models.CharField(default=0, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='resource',
            name='course_code',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='resource',
            name='download_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='resource',
            name='only_url',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='resource',
            name='url',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='resource',
            name='link',
            field=models.FileField(blank=True, upload_to='uploads/%Y/%m'),
        ),
    ]
