# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-30 04:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_auto_20171030_1210'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='course_id',
            field=models.IntegerField(default=-1),
        ),
        migrations.AddField(
            model_name='resource',
            name='upload_user_id',
            field=models.IntegerField(default=-1),
        ),
    ]
