# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-06 23:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_auto_20171106_2354'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='course_code',
        ),
    ]
