# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-08 17:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_auto_20171108_1641'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='college_id',
            field=models.PositiveIntegerField(blank=True, default=None),
        ),
    ]
