# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-06 23:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_remove_course_course_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='course_code',
            field=models.CharField(default=0, max_length=10),
            preserve_default=False,
        ),
    ]
