# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-07 00:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_course_course_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='course_code',
            new_name='code',
        ),
    ]
