# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-09 17:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_userprofile_college_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='IpVisitInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=20)),
                ('first_date', models.DateTimeField(auto_now_add=True)),
                ('latest_date', models.DateTimeField(auto_now=True)),
                ('visit_count', models.IntegerField(default=0)),
            ],
        ),
    ]
