# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-01 00:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0009_follow_follow_comment_follow_evaluation_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='credit',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=2),
            preserve_default=False,
        ),
    ]
