# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-05 16:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0011_resource_evaluation'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Evaluation',
        ),
        migrations.DeleteModel(
            name='R_Resource_Evaluation',
        ),
        migrations.DeleteModel(
            name='R_Resource_User_Download',
        ),
    ]
