# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-08 11:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0013_r_course_user_like'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='user_photo',
            field=models.ImageField(blank=True, null=True, upload_to='user_photo'),
        ),
    ]
