# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-10 15:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0014_emailverifyrecord'),
        ('backend', '0014_userprofile_user_photo'),
    ]

    operations = [
    ]
