# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-10 15:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0015_merge_20171210_2327'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='intro',
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
    ]
