# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-12 05:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0016_post_intro'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tongpao_Userprofile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(max_length=15, unique=True)),
                ('tongpao_username', models.CharField(blank=True, max_length=32)),
                ('phone_number', models.BigIntegerField(blank=True)),
                ('email', models.CharField(blank=True, max_length=254)),
                ('real_name', models.CharField(blank=True, max_length=50)),
                ('birthday', models.DateTimeField()),
                ('gender', models.CharField(blank=True, max_length=5)),
                ('grade', models.CharField(blank=True, max_length=10)),
                ('college', models.CharField(blank=True, max_length=30)),
                ('major', models.CharField(blank=True, max_length=20)),
                ('class_name', models.CharField(blank=True, max_length=20)),
                ('identification', models.CharField(blank=True, max_length=30)),
            ],
        ),
    ]
