# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-13 14:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0017_tongpao_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='follow',
            name='edit_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='update_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
